/**
 * Trial Signup Functions
 * 
 * Handles school trial signup requests from the landing page.
 * Sends notification emails and stores lead information in Firestore.
 */

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const nodemailer = require('nodemailer');

/**
 * Process trial signup request
 * 
 * Endpoint: POST /processTrialSignup
 * Body: { schoolName, adminName, email, phone, studentCount, message, timestamp }
 */
exports.processTrialSignup = functions.https.onRequest(async (req, res) => {
  // Enable CORS
  res.set('Access-Control-Allow-Origin', '*');
  res.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.set('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    res.status(204).send('');
    return;
  }

  // Only allow POST
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const { schoolName, adminName, email, phone, studentCount, message, timestamp } = req.body;

    // Validation
    if (!schoolName || !adminName || !email || !phone || !studentCount) {
      res.status(400).json({ error: 'Missing required fields' });
      return;
    }

    // Save to Firestore (for tracking leads)
    const db = admin.firestore();
    const leadRef = await db.collection('trial_signups').add({
      schoolName,
      adminName,
      email,
      phone,
      studentCount,
      message: message || '',
      timestamp: timestamp || admin.firestore.FieldValue.serverTimestamp(),
      status: 'pending',
      source: 'landing_page'
    });

    console.log(`Trial signup saved: ${leadRef.id} - ${schoolName} (${email})`);

    // Send notification email to EduSync team
    await sendNotificationEmail({
      schoolName,
      adminName,
      email,
      phone,
      studentCount,
      message,
      leadId: leadRef.id
    });

    // Send confirmation email to the user
    await sendConfirmationEmail({
      schoolName,
      adminName,
      email
    });

    res.status(200).json({
      success: true,
      message: 'Trial signup processed successfully',
      leadId: leadRef.id
    });
  } catch (error) {
    console.error('Error processing trial signup:', error);
    res.status(500).json({
      error: 'Internal server error',
      message: error.message
    });
  }
});

/**
 * Send notification email to EduSync team
 */
async function sendNotificationEmail({ schoolName, adminName, email, phone, studentCount, message, leadId }) {
  try {
    // Get email credentials from environment or Secret Manager
    const emailUser = process.env.EMAIL_USER || functions.config()?.email?.user;
    const emailPass = process.env.EMAIL_PASS || functions.config()?.email?.pass;

    if (!emailUser || !emailPass) {
      console.warn('Email credentials not configured. Skipping notification email.');
      return;
    }

    const transporter = nodemailer.createTransporter({
      service: 'gmail',
      auth: {
        user: emailUser,
        pass: emailPass
      }
    });

    const mailOptions = {
      from: `"EduSync Trial System" <${emailUser}>`,
      to: 'sales@edusync.ph', // Change to your sales email
      subject: `🎉 New Trial Signup: ${schoolName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #4F46E5;">New Trial Signup Request</h2>
          
          <div style="background: #F3F4F6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">School Information</h3>
            <p><strong>School Name:</strong> ${schoolName}</p>
            <p><strong>Administrator:</strong> ${adminName}</p>
            <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
            <p><strong>Phone:</strong> <a href="tel:${phone}">${phone}</a></p>
            <p><strong>Student Count:</strong> ${studentCount}</p>
          </div>

          ${message ? `
          <div style="background: #FEF3C7; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Additional Message</h3>
            <p style="white-space: pre-wrap;">${message}</p>
          </div>
          ` : ''}

          <div style="background: #DBEAFE; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Lead ID:</strong> ${leadId}</p>
            <p style="margin: 10px 0 0 0;"><strong>Recommended Plan:</strong> ${getRecommendedPlan(studentCount)}</p>
          </div>

          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #E5E7EB;">
            <p style="color: #6B7280; font-size: 12px; margin: 0;">
              This email was automatically generated by the EduSync Trial System.
            </p>
          </div>
        </div>
      `
    };

    await transporter.sendMail(mailOptions);
    console.log(`Notification email sent for lead ${leadId}`);
  } catch (error) {
    console.error('Error sending notification email:', error);
    // Don't throw - we don't want to fail the entire request if email fails
  }
}

/**
 * Send confirmation email to the user
 */
async function sendConfirmationEmail({ schoolName, adminName, email }) {
  try {
    const emailUser = process.env.EMAIL_USER || functions.config()?.email?.user;
    const emailPass = process.env.EMAIL_PASS || functions.config()?.email?.pass;

    if (!emailUser || !emailPass) {
      console.warn('Email credentials not configured. Skipping confirmation email.');
      return;
    }

    const transporter = nodemailer.createTransporter({
      service: 'gmail',
      auth: {
        user: emailUser,
        pass: emailPass
      }
    });

    const mailOptions = {
      from: `"EduSync Team" <${emailUser}>`,
      to: email,
      subject: `Welcome to EduSync! Your Trial Request is Received`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 20px; text-align: center; border-radius: 8px 8px 0 0;">
            <h1 style="color: white; margin: 0; font-size: 32px;">🎉 Welcome to EduSync!</h1>
          </div>

          <div style="padding: 40px 20px; background: white;">
            <p style="font-size: 16px; color: #374151; margin-bottom: 20px;">
              Hi ${adminName},
            </p>

            <p style="font-size: 16px; color: #374151; line-height: 1.6;">
              Thank you for your interest in EduSync for <strong>${schoolName}</strong>! 
              We're excited to help transform your school management.
            </p>

            <div style="background: #F3F4F6; padding: 20px; border-radius: 8px; margin: 30px 0;">
              <h3 style="margin-top: 0; color: #4F46E5;">What Happens Next?</h3>
              <ol style="color: #374151; line-height: 1.8; padding-left: 20px;">
                <li>Our team will review your request within <strong>24 hours</strong></li>
                <li>We'll set up a personalized demo school account with sample data</li>
                <li>You'll receive login credentials and a quick start guide via email</li>
                <li>Optional: Schedule a 30-minute onboarding call with our team</li>
              </ol>
            </div>

            <div style="background: #DBEAFE; padding: 20px; border-radius: 8px; margin: 30px 0;">
              <h3 style="margin-top: 0; color: #1E40AF;">💡 In the Meantime</h3>
              <p style="color: #374151; margin: 10px 0;">
                Check out our <a href="https://edusync-sis.web.app" style="color: #4F46E5; text-decoration: none; font-weight: bold;">video tutorials</a> 
                to see EduSync in action.
              </p>
              <p style="color: #374151; margin: 10px 0;">
                Have questions? Reply to this email or call us at <strong>+63 917 123 4567</strong>.
              </p>
            </div>

            <div style="text-align: center; margin-top: 40px;">
              <a href="https://edusync-sis.web.app" 
                 style="display: inline-block; background: #4F46E5; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 16px;">
                Visit EduSync Website
              </a>
            </div>

            <p style="font-size: 16px; color: #374151; margin-top: 40px;">
              Best regards,<br>
              <strong>The EduSync Team</strong>
            </p>
          </div>

          <div style="background: #F9FAFB; padding: 20px; text-align: center; border-radius: 0 0 8px 8px;">
            <p style="color: #6B7280; font-size: 12px; margin: 5px 0;">
              EduSync - School Information System
            </p>
            <p style="color: #6B7280; font-size: 12px; margin: 5px 0;">
              📧 hello@edusync.ph | 📱 +63 917 123 4567
            </p>
          </div>
        </div>
      `
    };

    await transporter.sendMail(mailOptions);
    console.log(`Confirmation email sent to ${email}`);
  } catch (error) {
    console.error('Error sending confirmation email:', error);
    // Don't throw - we don't want to fail the entire request if email fails
  }
}

/**
 * Get recommended plan based on student count
 */
function getRecommendedPlan(studentCount) {
  if (studentCount === '1-200' || studentCount === '201-500') {
    return '🟢 Starter Plan (₱1,999/month)';
  } else if (studentCount === '501-1000' || studentCount === '1001-1500') {
    return '🟣 Professional Plan (₱4,999/month)';
  } else {
    return '⭐ Enterprise Plan (Custom Pricing)';
  }
}
