import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeftIcon } from '@heroicons/react/24/outline';

/**
 * TermsOfService - Legal terms of service page
 * 
 * Covers usage rights, limitations, warranties, and legal agreements
 */
const TermsOfService: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 dark:from-gray-900 dark:via-indigo-950 dark:to-purple-950">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <button
            onClick={() => navigate('/')}
            className="inline-flex items-center text-sm text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 dark:hover:text-indigo-300 mb-4"
          >
            <ArrowLeftIcon className="h-4 w-4 mr-2" />
            Back to Home
          </button>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            Last Updated: November 8, 2025
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8 space-y-8">
          
          {/* Introduction */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Agreement to Terms</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              These Terms of Service ("Terms") constitute a legally binding agreement between you and EduSync 
              ("Company," "we," "us," or "our") regarding your use of the EduSync School Information System 
              (the "Service").
            </p>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to 
              these Terms, you may not access or use the Service.
            </p>
          </section>

          {/* Definitions */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Definitions</h2>
            <ul className="space-y-3 text-gray-700 dark:text-gray-300">
              <li><strong>"Service"</strong> refers to the EduSync School Information System, including the website, mobile applications, and all related services.</li>
              <li><strong>"School"</strong> refers to the educational institution that has subscribed to the Service.</li>
              <li><strong>"User"</strong> refers to any individual who accesses the Service, including school administrators, teachers, parents, and students.</li>
              <li><strong>"Content"</strong> refers to all data, information, text, graphics, photos, and other materials uploaded to or generated by the Service.</li>
              <li><strong>"Account"</strong> refers to a unique account created for you to access the Service.</li>
            </ul>
          </section>

          {/* Eligibility */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Eligibility</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              The Service is intended for use by educational institutions and their authorized users (administrators, 
              teachers, parents, and students). By using the Service, you represent and warrant that:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4 mt-4">
              <li>You are at least 18 years old, or you are a minor using the Service with parental/guardian consent and supervision</li>
              <li>You have the legal capacity to enter into these Terms</li>
              <li>You are authorized by your School to access the Service</li>
              <li>All information you provide is accurate and truthful</li>
            </ul>
          </section>

          {/* Account Registration */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Account Registration and Security</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
              To access certain features of the Service, you must create an account. You agree to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and promptly update your account information</li>
              <li>Maintain the security and confidentiality of your account credentials</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>Accept responsibility for all activities that occur under your account</li>
            </ul>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              We reserve the right to suspend or terminate accounts that violate these Terms or are inactive for extended periods.
            </p>
          </section>

          {/* Subscription and Payment */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Subscription and Payment</h2>
            
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">Trial Period</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              We may offer a free trial period for new Schools. The trial period duration and features will be specified 
              at the time of signup. We reserve the right to modify or discontinue free trials at any time.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">Paid Subscriptions</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
              After the trial period (if applicable), continued use of the Service requires a paid subscription. By subscribing, you agree to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
              <li>Pay all applicable subscription fees as specified in your plan</li>
              <li>Provide accurate and complete payment information</li>
              <li>Authorize us to charge your payment method on a recurring basis</li>
              <li>Pay all applicable taxes</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">Billing and Renewal</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date. 
              We will charge your payment method on file. Fees are non-refundable except as required by law or as explicitly 
              stated in these Terms.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">Cancellation</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              You may cancel your subscription at any time through your account settings or by contacting support. 
              Cancellation will take effect at the end of the current billing period. You will retain access to the 
              Service until the end of the paid period.
            </p>
          </section>

          {/* Acceptable Use */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Acceptable Use Policy</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree NOT to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the rights of others, including intellectual property rights</li>
              <li>Upload viruses, malware, or other harmful code</li>
              <li>Attempt to gain unauthorized access to the Service or other users' accounts</li>
              <li>Interfere with or disrupt the Service or servers</li>
              <li>Use the Service to harass, abuse, or harm others</li>
              <li>Collect or store personal data about other users without authorization</li>
              <li>Use automated scripts, bots, or scrapers without permission</li>
              <li>Reverse engineer, decompile, or disassemble the Service</li>
              <li>Resell or commercially exploit the Service without authorization</li>
            </ul>
          </section>

          {/* Content Ownership */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Content and Intellectual Property</h2>
            
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">Your Content</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              You retain ownership of all Content you upload to the Service. By uploading Content, you grant us a 
              worldwide, non-exclusive, royalty-free license to use, store, reproduce, and display your Content solely 
              for the purpose of providing and improving the Service.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">Our Content</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              The Service, including its design, features, functionality, text, graphics, logos, and software, is owned 
              by EduSync and protected by copyright, trademark, and other intellectual property laws. You may not copy, 
              modify, distribute, or create derivative works without our express written permission.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">DepEd Forms and Templates</h3>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              The Service provides templates for official DepEd forms (Form 137, Form 138, SF2, etc.). These forms are 
              based on publicly available DepEd templates and remain the property of the Department of Education. Our 
              implementation and formatting of these forms is proprietary to EduSync.
            </p>
          </section>

          {/* Data and Privacy */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Data and Privacy</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              Your use of the Service is subject to our Privacy Policy, which explains how we collect, use, and protect 
              your personal information. By using the Service, you consent to our collection and use of your data as 
              described in the Privacy Policy.
            </p>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              Schools are responsible for ensuring compliance with applicable data protection laws, including the Philippine 
              Data Privacy Act of 2012, when collecting and processing student and parent data through the Service.
            </p>
          </section>

          {/* Disclaimers and Warranties */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Disclaimers and Warranties</h2>
            <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-6">
              <p className="text-gray-900 dark:text-white font-semibold mb-2">IMPORTANT DISCLAIMER</p>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
                INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
              </p>
            </div>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              We do not warrant that:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4 mt-2">
              <li>The Service will be uninterrupted, timely, secure, or error-free</li>
              <li>The results obtained from using the Service will be accurate or reliable</li>
              <li>The quality of the Service will meet your expectations</li>
              <li>Any errors in the Service will be corrected</li>
            </ul>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              You acknowledge that you use the Service at your own risk. We recommend maintaining backup copies of your 
              data and verifying the accuracy of generated reports before official submission to DepEd.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Limitation of Liability</h2>
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-6">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, EDUSYNC AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, AND 
                LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, 
                INCLUDING LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.
              </p>
            </div>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              Our total liability to you for all claims arising from your use of the Service shall not exceed the amount 
              you paid us in the 12 months preceding the claim, or ₱5,000, whichever is greater.
            </p>
          </section>

          {/* Indemnification */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Indemnification</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              You agree to indemnify, defend, and hold harmless EduSync and its affiliates, officers, employees, agents, 
              and licensors from any claims, liabilities, damages, losses, costs, or expenses (including reasonable attorneys' 
              fees) arising out of or related to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4 mt-4">
              <li>Your use or misuse of the Service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any law or regulation</li>
              <li>Your violation of any third-party rights</li>
              <li>Content you upload or transmit through the Service</li>
            </ul>
          </section>

          {/* Service Modifications */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Service Modifications and Termination</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              We reserve the right to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4 mt-4">
              <li>Modify, suspend, or discontinue the Service (or any part thereof) at any time</li>
              <li>Change pricing with 30 days' notice</li>
              <li>Refuse service to anyone for any reason</li>
              <li>Terminate or suspend your account for violation of these Terms</li>
              <li>Remove or modify Content that violates these Terms or applicable laws</li>
            </ul>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              We will provide reasonable notice of material changes to the Service, except for urgent security or legal reasons.
            </p>
          </section>

          {/* Data Export and Portability */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Data Export and Portability</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              You may export your data at any time through the Service's export features. Upon termination of your subscription, 
              you will have 30 days to export your data. After this period, we may delete your data in accordance with our 
              data retention policies.
            </p>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              We recommend regularly exporting and backing up your data to ensure you maintain copies independent of the Service.
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Governing Law and Dispute Resolution</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the Republic of the Philippines, 
              without regard to its conflict of law provisions.
            </p>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              Any disputes arising out of or related to these Terms or the Service shall be resolved through good faith 
              negotiation. If negotiation fails, disputes shall be submitted to the appropriate courts in the Philippines.
            </p>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Changes to These Terms</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              We may revise these Terms at any time. We will provide notice of material changes by:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4 mt-4">
              <li>Posting the updated Terms on this page with a new "Last Updated" date</li>
              <li>Sending an email notification to registered users</li>
              <li>Displaying a prominent notice in the Service</li>
            </ul>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
              Your continued use of the Service after the effective date of revised Terms constitutes acceptance of those changes. 
              If you do not agree to the revised Terms, you must stop using the Service.
            </p>
          </section>

          {/* Severability */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Severability</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or 
              eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.
            </p>
          </section>

          {/* Entire Agreement */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Entire Agreement</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and EduSync regarding 
              the Service and supersede all prior agreements and understandings.
            </p>
          </section>

          {/* Contact Information */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Contact Us</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
              If you have questions about these Terms of Service, please contact us:
            </p>
            <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-6 space-y-2">
              <p className="text-gray-900 dark:text-white font-semibold">EduSync - School Information System</p>
              <p className="text-gray-700 dark:text-gray-300">
                Email: <a href="mailto:official@edusync.ph" className="text-indigo-600 dark:text-indigo-400 hover:underline">official@edusync.ph</a>
              </p>
              <p className="text-gray-700 dark:text-gray-300">
                Support: <a href="mailto:support@edusync.ph" className="text-indigo-600 dark:text-indigo-400 hover:underline">support@edusync.ph</a>
              </p>
              <p className="text-gray-700 dark:text-gray-300">
                Website: <a href="https://edusync.ph" className="text-indigo-600 dark:text-indigo-400 hover:underline">https://edusync.ph</a>
              </p>
            </div>
          </section>

          {/* Acknowledgment */}
          <section className="bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800 rounded-lg p-6">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Acknowledgment</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              BY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
