-- =====================================================
-- UPDATE TEACHERS WITH FIREBASE UIDs
-- Run this in Supabase SQL Editor after running
-- add-demo-teachers-to-firebase.cjs
-- =====================================================

-- Update teacher records with their Firebase UIDs
-- These UIDs were generated by the Firebase script on December 6, 2025

-- Teacher 1: Maria Santos - Mathematics
UPDATE teachers 
SET firebase_uid = 'gZfnO8iIJXRJIEoXJzOSv2X43uL2'
WHERE email = 'maria.santos@school.edu';

-- Also update the users table
UPDATE users 
SET firebase_uid = 'gZfnO8iIJXRJIEoXJzOSv2X43uL2'
WHERE email = 'maria.santos@school.edu';

-- Teacher 2: Juan Dela Cruz - Science
UPDATE teachers 
SET firebase_uid = 'SwFJl2Tu6QeXKLUGOSCLPC4wAcA2'
WHERE email = 'juan.delacruz@school.edu';

UPDATE users 
SET firebase_uid = 'SwFJl2Tu6QeXKLUGOSCLPC4wAcA2'
WHERE email = 'juan.delacruz@school.edu';

-- Teacher 3: Ana Reyes - English
UPDATE teachers 
SET firebase_uid = 'z5DL7ZQwHPN3Zq3OLb1gCx6s20Y2'
WHERE email = 'ana.reyes@school.edu';

UPDATE users 
SET firebase_uid = 'z5DL7ZQwHPN3Zq3OLb1gCx6s20Y2'
WHERE email = 'ana.reyes@school.edu';

-- Teacher 4: Pedro Garcia - Filipino
UPDATE teachers 
SET firebase_uid = 'uMRZoMnhtpeeYB5tGyUUaJgx9rI3'
WHERE email = 'pedro.garcia@school.edu';

UPDATE users 
SET firebase_uid = 'uMRZoMnhtpeeYB5tGyUUaJgx9rI3'
WHERE email = 'pedro.garcia@school.edu';

-- Teacher 5: Rosa Mendoza - TLE (Master Teacher)
UPDATE teachers 
SET firebase_uid = 'GjbNJ8TzV4ONe4QL2cvK5wCfj383'
WHERE email = 'rosa.mendoza@school.edu';

UPDATE users 
SET firebase_uid = 'GjbNJ8TzV4ONe4QL2cvK5wCfj383'
WHERE email = 'rosa.mendoza@school.edu';

-- Teacher 6: Carlos Villanueva - MAPEH
UPDATE teachers 
SET firebase_uid = 'am17hBof3SXWFTMmaRls6J1nHw92'
WHERE email = 'carlos.villanueva@school.edu';

UPDATE users 
SET firebase_uid = 'am17hBof3SXWFTMmaRls6J1nHw92'
WHERE email = 'carlos.villanueva@school.edu';

-- Teacher 7: Elena Fernandez - Araling Panlipunan
UPDATE teachers 
SET firebase_uid = 'u4aabtzYs3UxtPa0cvthy0ZXU4X2'
WHERE email = 'elena.fernandez@school.edu';

UPDATE users 
SET firebase_uid = 'u4aabtzYs3UxtPa0cvthy0ZXU4X2'
WHERE email = 'elena.fernandez@school.edu';

-- Teacher 8: Miguel Aquino - Values Education
UPDATE teachers 
SET firebase_uid = 'eTY6U5VwL1VPqmuwM1frmyAmCN93'
WHERE email = 'miguel.aquino@school.edu';

UPDATE users 
SET firebase_uid = 'eTY6U5VwL1VPqmuwM1frmyAmCN93'
WHERE email = 'miguel.aquino@school.edu';

-- =====================================================
-- VERIFICATION
-- =====================================================

-- Check teachers with Firebase UIDs
SELECT 
  name,
  email,
  firebase_uid,
  position,
  specialization
FROM teachers
WHERE firebase_uid IS NOT NULL
ORDER BY name;

-- Check users with Firebase UIDs
SELECT 
  name,
  email,
  firebase_uid,
  role
FROM users
WHERE firebase_uid IS NOT NULL 
  AND role = 'teacher'
ORDER BY name;

-- =====================================================
-- SUCCESS MESSAGE
-- =====================================================
SELECT '✅ Updated ' || COUNT(*) || ' teachers with Firebase UIDs' as message
FROM teachers 
WHERE firebase_uid IS NOT NULL;
